"""add review

Revision ID: d5c73d5484bf
Revises: 6966b8f7555c
Create Date: 2025-05-09 00:18:02.097031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c73d5484bf'
down_revision = '6966b8f7555c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_customer_id_customers'), 'reviews', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('fk_reviews_item_id_items'), 'reviews', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_item_id_items'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_customer_id_customers'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'item_id')
    op.drop_column('reviews', 'customer_id')
    # ### end Alembic commands ###
